final Map<String, String> genrePosters = {
  "Action":  '/3F2EXWF1thX0BdrVaKvnm6mAhqh.jpg', 
  "Adventure":  '/ebyxeBh56QNXxSJgTnmz7fXAlwk.jpg', 
  "Animation":  '/gbjK8p5S1aLXWCwOoXqr9aWZvqG.jpg', 
  "Comedy":  '/gbjK8p5S1aLXWCwOoXqr9aWZvqG.jpg', 
  "Crime":  '/3F2EXWF1thX0BdrVaKvnm6mAhqh.jpg', 
  "Documentary":  '/xJiF1zt3fBV14bzf1MNuzrZ4tTp.jpg', 
  "Drama":  '/vMxOmgmBGegjVObjlb8ugsjGgkD.jpg', 
  "Family":'/gbjK8p5S1aLXWCwOoXqr9aWZvqG.jpg', 
  "Fantasy":  '/AecGG1XVCmkk7fT10ko3FC0dLIP.jpg', 
  "History":  '/uRDu9DiTVf97z5sj6qesmyQpYji.jpg', 
  "Horror":  '/ykigHs1OIyqqV04zfFqIlSHp546.jpg', 
  "Music":'/w3Bi0wygeFQctn6AqFTwhGNXRwL.jpg', 
  "Mystery": '/sK3z0Naed3H1Wuh7a21YRVMxYqt.jpg', 
  "Romance":'/y6MgDckBAzPfvRDCR093UNaWItQ.jpg', 
  "Science Fiction": '/ebyxeBh56QNXxSJgTnmz7fXAlwk.jpg', 
  "TV Movie":'/7WL9YUEnzk7AbXyN0S4IJdl7Vgo.jpg', 
  "Thriller":  '/3F2EXWF1thX0BdrVaKvnm6mAhqh.jpg',
  "War":'/vMxOmgmBGegjVObjlb8ugsjGgkD.jpg',
  "Western":  '/hyc9gq0Oq5THKak7tB7oqC2Rd6z.jpg', 
};